### ISSUE TITLE
Repository enables the conduction of cyber-crime. Requesting immediate deletion of this repository

### ISSUE THREAD

**Issue by phath0m** [kogeki/the-scraper#13]
Hello,
    I am sure you are well aware of the fact that this repository serves no legitimate purpose other than to aid in the theft of online accounts. The contents of this repository are only relevant to actors currently engaged in operating popular info stealer malware targeting Discord and serve no legitimate cyber-security purpose. I understand you are relatively young, however, you must be aware that you bare some responsibility for the activities of those who use this program.

Legally speaking, you may be liable for the damage caused by users of this tool and may even face criminal charges in some jurisdictions. It would be wise to remove this repository and cease all affiliation with users of this software before this catches up with you. I don't think hiding behind "I didn't actually write the stealer" would get you that far, if this ever came to court.

**Comment by kogeki** [comment]
Hello @phath0m,

While I appreciate your concern and I thank you for bringing this issue to my attention, I don't think it is much of an issue. I am not a lawyer (obviously). Here is why:

1. The code is very simple and can be written by anyone with a very low skill level.
2. I don't think that law enforcement would ever go after me for this considering it does not even host any of the stolen data.
3. I like my GitHub stars <3

Thanks for your concern and I hope you have a great day!

**Comment by phath0m** [comment]
1. Sure, however, a large majority of the individuals employing these "grabbers" have very little technical skill. That doesn't change the fact that the *only* people using this are those who intend to commit crimes.
2. Sure, however, it is possible that this could come up during an investigation of any of the people using this. Regardless, that shouldn't matter. You shouldn't be helping these people simply due to the basic ethics surrounding this and the fact that your work is helping someone more efficiently utilize malware to steal accounts **and nobody else**.
3. This response answers the question I was ultimately trying to answer by submitting this issue. So you have no regard for the victims of the malware operators you are aiding by releasing this to the public? You would rather aid and abet criminals by providing them with the tools to do their "work" more efficiently, just for a few stars? 

You seem more than intelligent, so I'm sure you could go off and develop something else to get stars. I hope someday you realize the errors of your ways someday.

**Comment by Sharkbutt32** [comment]
LMAO WHAT :skull:

**Comment by Sharkbutt32** [comment]
please stfu @phath0m

**Comment by phath0m** [comment]
@Sharkbutt32 I would refrain from joining this discussion unless you have something productive to add. Simply commenting "stfu" brings nothing of value to this conversation nor does it address my concerns with the harmful activities this repository is aiding in.

**Comment by Sharkbutt32** [comment]
🤓🤓🤓🤓

**Comment by kogeki** [comment]
Locking because this is a stupid conversation. @phath0m, if you want to talk about this more or something, DM me on Discord. I am assuming you are from the Vaccinator so you already know what my Discord is.
