### ISSUE TITLE
Update Regex

### ISSUE THREAD

**Issue by Sharkbutt32** [kogeki/the-scraper#17]
![image](https://user-images.githubusercontent.com/109623849/183269058-15a481cf-09f3-497f-9bf9-92f407d6af5d.png)

**Comment by kogeki** [comment]
The regex that I am using here is taken from Hazard V2. Has he already updated it?

**Comment by Sharkbutt32** [comment]
yep

**Comment by kogeki** [comment]
Just checked and he is using the exact same regex as the one used here.

**Comment by Sharkbutt32** [comment]
weird
