### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aceeontop** [kogeki/the-scraper#26]
![image](https://user-images.githubusercontent.com/89152258/210239341-8d90c124-42f1-4296-8618-01250f51cf9a.png)
when doing node index.js

**Comment by kogeki** [comment]
This is due to an issue with your MySQL server. You probably need to use this other library that I don't remember the name of. I don't really care for this project anymore, so maybe someone else can help you.

**Comment by purpl3r0se** [comment]
> This is due to an issue with your MySQL server. You probably need to use this other library that I don't remember the name of. I don't really care for this project anymore, so maybe someone else can help you.

fixed it for him, just wiped database and user and redid it.

**Comment by kogeki** [comment]
> > This is due to an issue with your MySQL server. You probably need to use this other library that I don't remember the name of. I don't really care for this project anymore, so maybe someone else can help you.
> 
> fixed it for him, just wiped database and user and redid it.

glad you figured it out.
